name: On Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch or tag to deploy'
        required: true
      env:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - stg
          - prod

jobs:
  deploy-onboarding-api:
    name: Release Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-deploy-pipe.yml@main
    with:
      branch: ${{ inputs.branch }}
      env: ${{ inputs.env }}
      gb_project_key: ${{ vars.GB_PK }}
      gb_app_name: ${{ vars.GB_APP_NAME }}