name: On Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select environment to deploy to'
        required: true
        type: choice
        default: stg
        options:
          - stg
          - prod

permissions:
  id-token: write
  contents: write
  
jobs:
  deploy-onboarding-api:
    name: Release Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-deploy-pipe.yml@main
    with:
      branch: ${{ github.ref_name }}
      env: ${{ inputs.env }}
      gb_project_key: ${{ vars.GB_PK }}
      gb_app_name: ${{ vars.GB_APP_NAME }}