name: On Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to deploy from (e.g., v1.2.3)'
        required: true
        type: string
      env:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - stage
          - prod

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}

      - name: Display deployment target
        run: echo "Deploying tag ${{ inputs.tag }} to ${{ inputs.env }} environment"
