name: On push to main

on:
  push:
    branches:
      - main

jobs:
  sanity-check:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable corepack and install dependencies
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test:unit

      - name: Run integration tests
        run: yarn test:integration

  release:
    name: Release application
    runs-on: ubuntu-latest
    needs: sanity-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Enable corepack and install dependencies
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Build binaries
        run: yarn build

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release

  dockerize:
    name: Dockerize application
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to fetch tags

      - name: Get released tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Checkout code at tag
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_tag.outputs.tag }}

      - name: Build Docker image
        run: docker build -t std-onboarding-api:${{ steps.get_tag.outputs.tag }} .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050752613795:role/STDServiceRoleForGitHub
          aws-region: us-east-1
