name: On Pull Request

on:
  pull_request:
    branches:
      - main
    types:
        - opened
        - synchronize
        - reopened
        - edited

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean and install
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Build binaries
        run: yarn build
