name: On push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean and install
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test

      - name: Release a new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
