name: On push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean and install
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Build binaries
        run: yarn build

      - name: Upload artifacts for release
        id: artifacts-for-release
        uses: actions/upload-artifact@v4
        with:
          name: root-folder
          path: /

  release:
    name: Release application
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts for release
        uses: actions/download-artifact@v4
        with:
          name: root-folder
          path: /

      - name: Release a new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
