name: On Pull Request

on:
  pull_request:
    branches:
      - main
    types:
        - opened
        - synchronize
        - reopened
        - edited

jobs:
  build-inboarding-api:
    name: Build Inboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-pipe.yml@main
    with:
      node-version: "22"
      release-mode: false
    secrets: inherit