name: On push to main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release-onboarding-api:
    name: Release Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-pipe.yml@v1.3.0
    with:
      node-version: "22"
      release-mode: true
    secrets: inherit