name: On Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  build-onboarding-api:
    name: Build Onboarding API
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-nestjs-pipe.yml@v1.4.2
    with:
      node-version: "22"
      release-mode: false
    secrets: inherit