name: On push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean and install
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Build binaries
        run: yarn build

  release:
    name: Release application
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean and install
        run: yarn install --frozen-lockfile
        
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Release a new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
