name: On push to tales

on:
  push:
    branches:
      - tales

permissions:
  id-token: write
  contents: write

jobs:
  tales:
    name: teles
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050752613795:role/STDServiceRoleForGitHub
          aws-region: us-east-1