name: On push to tales

on:
  push:
    branches:
      - tales

permissions:
  id-token: write
  contents: write

jobs:
  tales:
    name: teles
    runs-on: ubuntu-latest
    steps:
      - name: Debug OIDC Token (print `sub` claim)
        id: oidc-debug
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken("sts.amazonaws.com");
            const [header, payload] = token.split('.').slice(0, 2).map(part => Buffer.from(part, 'base64url').toString('utf8'));
            const sub = JSON.parse(payload).sub;
            core.info(`OIDC sub claim: ${sub}`);

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050752613795:role/STDServiceRoleForGitHub
          aws-region: us-east-1